### ISSUE TITLE
Corrections for escrow contract instructions

### ISSUE THREAD

**Issue by whoabuddy** [friedger/clarity-smart-contracts#3]
Hey Friedger! First off, thank you for putting all this together, I think it's a great resource!

@HaroldDavis3 and I were walking through the setup on his machine, and I noted a few differences in his experience versus what you have in the instructions. A few notes below:

__HTTPS links versus SSH__

There are a few people coming up with "permissions errors" when they try to follow the instructions, and it's because they are using the SSH links in the tutorial versus HTTPS without having SSH configured. It might be worth either noting this at the beginning for people to use the correct link?

__Wrong repo on stacks-transactions-js__

Under Stacks Transaction library for Javascript, the repo listed is actually the stacks-blockchain one when it should be stacks-transactions-js:
```
git clone git@github.com:blockstack/stacks-blockchain.git <-- the *other* stacks-thing :)
cd stacks-transactions-js
git checkout feature/tx-broadcast
```

__Moving around directories with `cd ..`__ 

This part may be a bit confusing for people who are downloading/using LInux for the first time, as they may not realize what directory they are in or what's happening. If they `cd ..` in the wrong place or a new terminal window, it creates an issue.

Maybe have them create a terminal window for each `git clone` operation? That way it'd land in their home directory every time?

**Comment by friedger** [comment]
Thank you for your input. I have updated the documentation to the latest version of blockstack-core and addressed the issues you mentioned.
